services:
  cloudflare-bypass:
    image: ghcr.io/tsuk1ko/cloudflarebypassforscraping-legacy:latest
    container_name: cloudflare-bypass
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "2"
    shm_size: 128m
    restart: unless-stopped
